name: Run on Remote Machine via SSH

on:
  push:
    branches:
      - main

jobs:
  remote-job:
    runs-on: self-hosted  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.197.201.247 >> ~/.ssh/known_hosts
          

      - name: Execute Command on Remote Machine
        run: |
          echo $secrets.SSH_PRIVATE_KEY

      - name: Copy File to Remote Machine
        env:
         REMOTE_USER: ubuntu              
         REMOTE_HOST: 54.197.201.247          
         LOCAL_FILE_PATH: demofile.txt
         REMOTE_DEST_PATH: /home/ubuntu/  
        run: |
         scp -o StrictHostKeyChecking=no \
            $LOCAL_FILE_PATH $REMOTE_USER@$REMOTE_HOST:$REMOTE_DEST_PATH

          
