name: Run on Remote Machine via SSH

on:
  push:
    branches:
      - main

jobs:
  remote-job:
    runs-on: self-hosted  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.197.201.247 >> ~/.ssh/known_hosts

      - name: Execute Command on Remote Machine
        run: |
          ssh -i sshkey ubuntu@54.197.201.247 "hostname && echo 'Hello from remote machine'"
