name: Run on Remote Machine via SSH

on:
  push:
    branches:
      - main

jobs:
  remote-job:
    runs-on: self-hosted  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.197.201.247 >> ~/.ssh/known_hosts
          

      - name: Execute Command on Remote Machine
        run: |
          echo $secrets.SSH_PRIVATE_KEY

      

      - name: Verify File Exists on Remote Machine
        env:
         REMOTE_USER: ubuntu              
         REMOTE_HOST: 54.197.201.247  
         REMOTE_FILE_PATH: /home/ubuntu/demofile.txt  # Full path to the copied file
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST \
          "[ -f $REMOTE_FILE_PATH ] && echo 'File exists: $REMOTE_FILE_PATH' || echo 'File does not exist: $REMOTE_FILE_PATH'"

          
